define([], function () {
    return {
        Type: 'OK',
        Size: null,
        Title: 'Başlık',
        MessageText: 'Mesaj',
        MessageType: 'default',
        MessageIcon: '',
        MessageIconSize: 5,
        InputType:'text',
        OkButtonText: 'Tamam',
        OkButtonIcon: '',
        OkButtonClass: 'primary',
        OkButtonFunction: '',
        OkButtonFunctionParams: {},
        YesButtonText: 'Evet',
        YesButtonIcon: 'fa fa-check',
        YesButtonClass: 'success',
        YesButtonFunction: '',
        YesButtonFunctionParams: {},
        NoButtonText: 'Hayır',
        NoButtonIcon: 'fa fa-times',
        NoButtonClass: 'danger',
        NoButtonFunction: '',
        NoButtonFunctionParams: {},
        CancelButtonText: 'İptal',
        CancelButtonIcon: 'fa fa-ban',
        CancelButtonClass: 'warning',
        CancelButtonFunction: '',
        CancelButtonFunctionParams: {},
        Callback: null,
        CloseButton: true,
        InputOptions: {}
    };
});